import "./globals.css";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import ToasterContext from "./context/ToasterContext";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-Auth App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={`${inter.className} flex flex-col `}>
        <AuthProvider>
          <ToasterContext />
          <Navbar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
